branches:
  only:
  - master

language: r
pandoc_version: 2.2
sudo: false
dist: trusty
cache:
  packages: true
  directories:
    - $HOME/.TinyTeX

matrix:
  include:
  - r: devel
  - r: release
    after_success:
      - Rscript -e 'covr::codecov()'
  - r: release
    name: tidy-devel
    before_script:
      - Rscript -e "remotes::install_github('tidyverse/dplyr')"
      - Rscript -e "remotes::install_github('tidyverse/tidyr')"
      - Rscript -e "remotes::install_github('tidyverse/ggplot2')"
  - r: oldrel

addons:
  apt:
    update: true
    sources:
      - sourceline: "ppa:cran/imagemagick"
    packages:
      - ghostscript
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - gsfonts

before_install:
  - wget -qO- https://github.com/yihui/tinytex/raw/master/tools/download-travis-linux.sh | sh

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
