---
title: "Tech Report Title"
shorttitle: "A Short Title"
subtitle: "Technical Report #XX-XX"
date: "`r format(Sys.Date(), '%B %Y')`"
program: "DLM"
knit: bookdown::render_book
output: ratlas::techreport_pdf
internal: false
manual: false
bibliography: ["bib/refs.bib", "bib/packages.bib"]
biblio-style: apa
biblatexoptions:
  - sortcites
csl: csl/apa.csl
link-citations: yes
lot: true
lof: true
subparagraph: yes
mainfont: Arial
fontsize: 11pt
acknowledgements: >
  `r if (knitr::is_latex_output()) ratlas::inc("front-matter/preface.Rmd")`
copyright: "Copyright \\copyright\\ 2020 Accessible Teaching, Learning, and Assessment Systems (ATLAS)"
---

```{r setup, include = FALSE}
needed_packages <- c("ratlas", "knitr", "english")
load_packages <- function(x) {
  if (!(x %in% installed.packages())) {
    install.packages(x, repos = "https://cran.rstudio.com/")
  }
  
  suppressPackageStartupMessages(require(x, character.only = TRUE))
}
vapply(needed_packages, load_packages, logical(1))

options(knitr.kable.NA = "")
options(knitr.table.format = "latex")
set_theme(font = "Arial Narrow", plot_margin = ggplot2::margin(0, 10, 10, 10))
```




\newpage

# References

```{r write-packages, include = FALSE}
if (!file.exists("bib/packages.bib")) file.create("bib/packages.bib")
suppressWarnings(
  knitr::write_bib(c(.packages()), "bib/packages.bib")
)
```

\printbibliography[heading=none]

\setlength{\parindent}{15pt}
\setlength{\leftskip}{0pt}
